## Numpy

In [1]:
 pip install numpy

### Built in functions

In [1]:
import numpy as np

In [3]:
range(5)


range(0, 5)

In [4]:
np.arange(0,200,5)

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100, 105, 110, 115, 120, 125,
       130, 135, 140, 145, 150, 155, 160, 165, 170, 175, 180, 185, 190,
       195])

##  one dimensional array 1D

In [5]:
m1=np.array([1,2,3,4,5])

In [6]:
print(m1)

[1 2 3 4 5]


In [7]:
m2=np.array([6,7,8,9,10])

In [8]:
m3=print(m1+m2)

[ 7  9 11 13 15]


In [9]:
type(m1)

numpy.ndarray

In [10]:
m2=np.zeros(5)
print(m2)

[0. 0. 0. 0. 0.]


## 2D

In [14]:
m7=np.array([[1,3],[2,4]])

In [15]:
m7

array([[1, 3],
       [2, 4]])

In [16]:
m8=np.array([[8,6],[9,3]])

In [17]:
m8

array([[8, 6],
       [9, 3]])

In [18]:
m7+m8

array([[ 9,  9],
       [11,  7]])

### matrics  should be same for adding,subtract 

In [22]:
m9=np.array([[1,2,3],[4,5,6]])

In [23]:
m9+m8

ValueError: operands could not be broadcast together with shapes (2,3) (2,2) 

In [2]:
m10=np.array([[1,2,3],[4,5,6],[8,7,9]])

In [3]:
m11=np.array([[4,5,6],[9,8,7],[2,5,8]])

In [4]:
m11.shape

(3, 3)

In [5]:
m10

array([[1, 2, 3],
       [4, 5, 6],
       [8, 7, 9]])

In [6]:
m11

array([[4, 5, 6],
       [9, 8, 7],
       [2, 5, 8]])

In [7]:
m10+m11

array([[ 5,  7,  9],
       [13, 13, 13],
       [10, 12, 17]])

In [8]:
m10*m11

array([[ 4, 10, 18],
       [36, 40, 42],
       [16, 35, 72]])

### random

In [9]:
arr=np.random.rand(2,3)

In [10]:
arr

array([[0.80208558, 0.94183591, 0.30169551],
       [0.51818895, 0.52821287, 0.06499082]])

## Randint

In [21]:
np.random.randint(1,10,5)

array([4, 9, 5, 4, 9])

In [23]:
np.random.randint(1,10,(2,4))

array([[2, 8, 4, 4],
       [1, 7, 8, 5]])

In [24]:
np.random.randint(100,size=(2,3))

array([[ 6, 19, 50],
       [86, 70, 33]])

In [24]:
np.random.randint(100,(2,3))

ValueError: low >= high

####  randint  will give int values  and  rand  will give float values

In [25]:
np.random.rand(2,3)*100

array([[65.45342708, 79.2375986 , 31.13520163],
       [61.98293107,  0.63932141, 50.68023408]])

In [26]:
np.random.randint(3,5)*100

300

## Randn

#### ranges for  uniform distibution (-3 to +3)

In [27]:
np.random.randn(5)

array([-0.35986929,  0.77088994, -0.23840296,  0.05691557, -0.55103651])

In [28]:
np.random.randn(5,3)

array([[ 1.05335351,  1.26328837, -0.24918134],
       [-0.13821029, -0.16062844,  0.91944688],
       [ 1.07747266,  0.08436038,  0.85635437],
       [ 1.01139338,  0.22416848, -0.40019456],
       [ 0.2381109 ,  1.06269122, -1.37576762]])

In [29]:
arr=np.array([1.0,2.0,3.0,4.0,5.0])
print(arr)
print(type(arr))
print(arr.dtype)

[1. 2. 3. 4. 5.]
<class 'numpy.ndarray'>
float64


In [30]:
arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))
print(arr.dtype)

[1 2 3 4 5]
<class 'numpy.ndarray'>
int32


In [31]:
arr=np.array([1,2,6,4,5])
print(arr)
print(type(arr))
print(arr.dtype)

[1 2 6 4 5]
<class 'numpy.ndarray'>
int32


## Identity matrics

### eye  is used only for identity matrics

In [32]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [33]:
i=np.eye(3)

In [34]:
i.dtype

dtype('float64')

## linspace

In [35]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [36]:
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

## Array

In [37]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])

In [38]:
print(arr1+arr2)
print(arr1*arr2)
print(arr1**arr2)


[5 7 9]
[ 4 10 18]
[  1  32 729]


### zeros and onoes

In [39]:
np.zeros(3)

array([0., 0., 0.])

In [40]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [41]:
np.ones(4)

array([1., 1., 1., 1.])

In [42]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [43]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

## matrix multiplication

In [44]:
A1 = np.array([[1,2],[3,4]])
B1 = np.array([[5,6],[7,8]])

In [45]:
np.matmul(A1,B1)

array([[19, 22],
       [43, 50]])

In [46]:
A1.dot(B1)

array([[19, 22],
       [43, 50]])

In [47]:
arr = np.array([[1, 5, 6],
                [4, 7, 2],
                [3, 1, 9]])

In [48]:
print("max values in array",arr.max())
print("min values in array",arr.min())
print("sum values in array",arr.sum())

max values in array 9
min values in array 1
sum values in array 38


## axis =1 is used for row wise operation , axis = 0 is used for column wise operation

In [49]:
print("Row-wise maximum max values ",arr.max(axis= 1))
print("Row-wise maximum min values",arr.min(axis= 1))
print("Row-wise maximum sum values",arr.sum(axis= 1))

Row-wise maximum max values  [6 7 9]
Row-wise maximum min values [1 2 1]
Row-wise maximum sum values [12 13 13]


In [50]:
print("Row-wise maximum max values ",arr.max(axis= 0))
print("Row-wise maximum min values",arr.min(axis= 0))
print("Row-wise maximum sum values",arr.sum(axis= 0))

Row-wise maximum max values  [4 7 9]
Row-wise maximum min values [1 1 2]
Row-wise maximum sum values [ 8 13 17]


In [51]:
arr3=np.array([2,5,4,3,6])

In [52]:
arr3.mean()

4.0

In [53]:
arr3.var()

2.0

In [54]:
arr3.std()

1.4142135623730951

In [55]:
arr = np.array([[1, 5, 6],
                [4, 7, 2],
                [3, 1, 9]])

In [56]:
print("mean",arr.mean(axis = 0))
print("std",arr.std(axis = 0))
print("variance",arr.var(axis = 0))

mean [2.66666667 4.33333333 5.66666667]
std [1.24721913 2.49443826 2.86744176]
variance [1.55555556 6.22222222 8.22222222]


In [57]:
print("mean",arr.mean(axis = 1))
print("std",arr.std(axis = 1))
print("variance",arr.var(axis = 1))

mean [4.         4.33333333 4.33333333]
std [2.1602469  2.05480467 3.39934634]
variance [ 4.66666667  4.22222222 11.55555556]


In [58]:
m1=np.array([1,2,3,4,5,6])

In [59]:
m1.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [60]:
m1.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [61]:
m3=np.array([[1,2],[3,4],[2,3],[5,6],[8,5]])
print(m3.shape)
print(m3)

(5, 2)
[[1 2]
 [3 4]
 [2 3]
 [5 6]
 [8 5]]


In [62]:
m3.reshape(2,5)

array([[1, 2, 3, 4, 2],
       [3, 5, 6, 8, 5]])

## stacking arrays

In [63]:
arr1 = np.array([[1,2],[3,4]])   
arr2 = np.array([[10,20],[30,40]]) 

In [64]:
## horizantal stack
np.hstack((arr1,arr2))

array([[ 1,  2, 10, 20],
       [ 3,  4, 30, 40]])

In [65]:
## vertical stack
np.vstack((arr1,arr2))

array([[ 1,  2],
       [ 3,  4],
       [10, 20],
       [30, 40]])

In [66]:
np.concatenate((arr1,arr2),axis=0)

array([[ 1,  2],
       [ 3,  4],
       [10, 20],
       [30, 40]])

In [63]:
np.concatenate((arr1,arr2),axis=1)

array([[ 1,  2, 10, 20],
       [ 3,  4, 30, 40]])