In [1]:
import time

In [3]:
time.time()

1652071960.086004

In [6]:
time.time()

1652072002.924431

In [13]:
test=10000000
l1=range(test)
l2=range(test)
start=time.time()
reslt=[x+y for x,y in zip(l1,l2)]
end_time=time.time()
print((end_time-start))

2.4385316371917725


In [12]:
import numpy as np

In [15]:
arr1=np.arange(test)
arr2=np.arange(test)
start=time.time()
result=arr1+arr2
print((time.time()-start))

0.026942968368530273


### in list  we can add any  int & float &string values it can store  any data
#### bbut in numpy it can store  any one   but not mix

In [22]:
l1=[1,2.0,3]
l2=[1,2,'a']
n1=np.array(l1)
print("numpy.array n1",n1)
n2=np.array(l2)
print("numpy.array n2",n2)

numpy.array n1 [1. 2. 3.]
numpy.array n2 ['1' '2' 'a']


In [23]:
n2.dtype

dtype('<U11')

In [27]:
n3=np.array(l1,dtype='<U11')
print(n3)

['1' '2.0' '3']


In [29]:
n4=np.array(l1,dtype="int")

In [30]:
n4

array([1, 2, 3])

####  accesing the particular eement by using indexing

In [5]:
n5=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [6]:
n5

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
import numpy as np

In [8]:
print(["n5[0][2]",n5[0][2]])
print(["n5[2][1]",n5[2][1]])
print(["n5[1][0]",n5[1][0]])

['n5[0][2]', 3]
['n5[2][1]', 8]
['n5[1][0]', 4]


##  xmple

In [54]:
age=[10,56,89,74,45,14,50]

In [55]:
arr=np.array(age)
arr

array([10, 56, 89, 74, 45, 14, 50])

In [56]:
arr>45

array([False,  True,  True,  True, False, False,  True])

In [57]:
arr2=arr[arr>55]

In [58]:
arr2

array([56, 89, 74])

In [60]:
age=[10,56,89,74,45,14,50,45,89,12,21,31]

In [61]:
arr[(arr<17)|(arr>60)]

array([10, 89, 74, 14])

In [64]:
arr[((arr%2)==0)&(arr>55)]

array([56, 74])

In [83]:
arr[((arr%3)==0)&(arr>15)]

array([45])

### flatten   ravel

In [98]:
arr=np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [99]:
a1=arr.flatten()
print("arr after flattering",a1)
a1[2]=14
print("arr after modify",a1)
print("actual array",arr)

arr after flattering [1 2 3 4 5 6]
arr after modify [ 1  2 14  4  5  6]
actual array [[1 2 3]
 [4 5 6]]


In [100]:
a1=arr.ravel()
print("a1 after flattering",a1)
a1[2]=14
print("a1 after modify",a1)
print("actual array",arr)

a1 after flattering [1 2 3 4 5 6]
a1 after modify [ 1  2 14  4  5  6]
actual array [[ 1  2 14]
 [ 4  5  6]]


### index slicing method

In [103]:
arr1=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [111]:
arr1[1:3,1:3]

array([[ 6,  7],
       [10, 11]])

In [112]:
arr1[1:4,1:4]

array([[ 6,  7,  8],
       [10, 11, 12],
       [14, 15, 16]])

In [113]:
arr1[1::]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

### transpose   chaging from rows to column

In [116]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [118]:
b=np.transpose(arr)
b

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

###  broadcasting

In [120]:
arr1=np.array([[2,3,4,8],[4,5,6,8]])
arr2=np.array([4,5,6,9])

In [121]:
arr1+arr2

array([[ 6,  8, 10, 17],
       [ 8, 10, 12, 17]])

In [13]:
arr1=np.array([[2,3,4,8],[4,5,6,8]])
arr2=np.array([[4,5,6,9],[8,4,7,5]])

In [14]:
arr1+arr2

array([[ 6,  8, 10, 17],
       [12,  9, 13, 13]])